sudo: required
services:
  - docker
before_install:
  - L=$PWD/flynn && curl -sSL -A "`uname -sp`" https://dl.flynn.io/cli | zcat >$L && chmod +x $L
  - export PATH=$PATH:$PWD/
  - flynn cluster add -p $FLYNN_CLUSTER_ADD
  - sudo mkdir -p /etc/docker/certs.d/docker.apps.ethanl.ee
  - sudo cp /home/travis/.flynn/ca-certs/default.pem /etc/docker/certs.d/docker.apps.ethanl.ee/ca.crt
  - sudo service docker stop
  - sudo service docker start
  - flynn docker set-push-url
  - flynn docker login
  - echo $DOCKER_ENV > .env
script: ./docker_setup.sh
after_script: flynn -a humans-harangue-burlington docker push rmi_web
