version: '3'
services:
  db:
    image: postgres
  web:
    env_file: .env
    build:
        context: .
        dockerfile: docker/rails_dockerfile
    command: rails s
    volumes:
      - .:/rmi
    ports:
      - "3000:3000"
    depends_on:
      - db
