// BuildingType ActionTypes
export const ADD_BUILDING_TYPE = 'ADD_BUILDING_TYPE';
export const CHANGE_BUILDING_TYPE_NAME = 'CHANGE_BUILDING_TYPE_NAME';
export const REMOVE_BUILDING_TYPE = 'REMOVE_BUILDING_TYPE';
export const SAVE_BUILDING_TYPE = 'SAVE_BUILDING_TYPE';

// Building ActionTypes
export const ADD_BUILDING = 'ADD_BUILDING';
export const CHANGE_BUILDING_NAME = 'CHANGE_BUILDING_NAME';
export const REMOVE_BUILDING = 'REMOVE_BUILDING';
export const SAVE_BUILDING = 'SAVE_BUILDING';

// Question ActionTypes
export const ADD_QUESTION = 'ADD_QUESTION';
export const ADD_OPTION = 'ADD_OPTION';
export const ADD_CATEGORY = 'ADD_CATEGORY';

export const EDIT_QUESTION = 'EDIT_QUESTION';
export const EDIT_OPTION = 'EDIT_OPTION';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';

export const REMOVE_QUESTION = 'REMOVE_QUESTION';
export const REMOVE_OPTION = 'REMOVE_OPTION';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';

export const SAVE_QUESTION = 'SAVE_QUESTION';
export const SAVE_OPTION = 'SAVE_OPTION';
export const SAVE_CATEGORY = 'SAVE_CATEGORY';
